// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/orderer/orderer.proto

package orderer

import (
	common "github.com/ddr4869/minifab/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BootstrapRequest - 네트워크 부트스트랩 요청
type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigtxPath  string                 `protobuf:"bytes,1,opt,name=configtx_path,json=configtxPath,proto3" json:"configtx_path,omitempty"` // configtx.yaml 파일 경로
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`                               // 프로파일 이름
	GenesisFile   string                 `protobuf:"bytes,3,opt,name=genesis_file,json=genesisFile,proto3" json:"genesis_file,omitempty"`    // 제네시스 파일 저장 경로
	MspId         string                 `protobuf:"bytes,4,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`                      // MSP ID
	MspPath       string                 `protobuf:"bytes,5,opt,name=msp_path,json=mspPath,proto3" json:"msp_path,omitempty"`                // MSP 경로
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapRequest) GetConfigtxPath() string {
	if x != nil {
		return x.ConfigtxPath
	}
	return ""
}

func (x *BootstrapRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *BootstrapRequest) GetGenesisFile() string {
	if x != nil {
		return x.GenesisFile
	}
	return ""
}

func (x *BootstrapRequest) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

func (x *BootstrapRequest) GetMspPath() string {
	if x != nil {
		return x.MspPath
	}
	return ""
}

// BootstrapResponse - 부트스트랩 응답
type BootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GenesisFile   string                 `protobuf:"bytes,3,opt,name=genesis_file,json=genesisFile,proto3" json:"genesis_file,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *BootstrapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BootstrapResponse) GetGenesisFile() string {
	if x != nil {
		return x.GenesisFile
	}
	return ""
}

func (x *BootstrapResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// BlockRequest - 블록 요청
type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{2}
}

func (x *BlockRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// BlockResponse - 블록 응답
type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Block         *common.Block          `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{3}
}

func (x *BlockResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *BlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlockResponse) GetBlock() *common.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// ChannelRequest - 채널 생성 요청
type ChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelName   string                 `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ConfigtxPath  string                 `protobuf:"bytes,2,opt,name=configtx_path,json=configtxPath,proto3" json:"configtx_path,omitempty"`
	Profile       string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRequest) Reset() {
	*x = ChannelRequest{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRequest) ProtoMessage() {}

func (x *ChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRequest.ProtoReflect.Descriptor instead.
func (*ChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ChannelRequest) GetConfigtxPath() string {
	if x != nil {
		return x.ConfigtxPath
	}
	return ""
}

func (x *ChannelRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// ChannelResponse - 채널 생성 응답
type ChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResponse) Reset() {
	*x = ChannelResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResponse) ProtoMessage() {}

func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResponse.ProtoReflect.Descriptor instead.
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *ChannelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// ChannelInfoRequest - 채널 정보 요청
type ChannelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfoRequest) Reset() {
	*x = ChannelInfoRequest{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfoRequest) ProtoMessage() {}

func (x *ChannelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfoRequest.ProtoReflect.Descriptor instead.
func (*ChannelInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelInfoRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// ChannelInfoResponse - 채널 정보 응답
type ChannelInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Info          *ChannelInfo           `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfoResponse) Reset() {
	*x = ChannelInfoResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfoResponse) ProtoMessage() {}

func (x *ChannelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfoResponse.ProtoReflect.Descriptor instead.
func (*ChannelInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelInfoResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *ChannelInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChannelInfoResponse) GetInfo() *ChannelInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ChannelInfo - 채널 정보
type ChannelInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChannelId         string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Height            uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	CurrentBlockHash  []byte                 `protobuf:"bytes,3,opt,name=current_block_hash,json=currentBlockHash,proto3" json:"current_block_hash,omitempty"`
	PreviousBlockHash []byte                 `protobuf:"bytes,4,opt,name=previous_block_hash,json=previousBlockHash,proto3" json:"previous_block_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelInfo) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChannelInfo) GetCurrentBlockHash() []byte {
	if x != nil {
		return x.CurrentBlockHash
	}
	return nil
}

func (x *ChannelInfo) GetPreviousBlockHash() []byte {
	if x != nil {
		return x.PreviousBlockHash
	}
	return nil
}

// OrdererStatusRequest - Orderer 상태 요청
type OrdererStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeChannels bool                   `protobuf:"varint,1,opt,name=include_channels,json=includeChannels,proto3" json:"include_channels,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrdererStatusRequest) Reset() {
	*x = OrdererStatusRequest{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdererStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdererStatusRequest) ProtoMessage() {}

func (x *OrdererStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdererStatusRequest.ProtoReflect.Descriptor instead.
func (*OrdererStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{9}
}

func (x *OrdererStatusRequest) GetIncludeChannels() bool {
	if x != nil {
		return x.IncludeChannels
	}
	return false
}

// OrdererStatusResponse - Orderer 상태 응답
type OrdererStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OrdererStatus *OrdererStatus         `protobuf:"bytes,3,opt,name=orderer_status,json=ordererStatus,proto3" json:"orderer_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdererStatusResponse) Reset() {
	*x = OrdererStatusResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdererStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdererStatusResponse) ProtoMessage() {}

func (x *OrdererStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdererStatusResponse.ProtoReflect.Descriptor instead.
func (*OrdererStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{10}
}

func (x *OrdererStatusResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *OrdererStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrdererStatusResponse) GetOrdererStatus() *OrdererStatus {
	if x != nil {
		return x.OrdererStatus
	}
	return nil
}

// OrdererStatus - Orderer 상태
type OrdererStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrdererId     string                 `protobuf:"bytes,1,opt,name=orderer_id,json=ordererId,proto3" json:"orderer_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Channels      []string               `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdererStatus) Reset() {
	*x = OrdererStatus{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdererStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdererStatus) ProtoMessage() {}

func (x *OrdererStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdererStatus.ProtoReflect.Descriptor instead.
func (*OrdererStatus) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{11}
}

func (x *OrdererStatus) GetOrdererId() string {
	if x != nil {
		return x.OrdererId
	}
	return ""
}

func (x *OrdererStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OrdererStatus) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *OrdererStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *OrdererStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_orderer_orderer_proto protoreflect.FileDescriptor

const file_proto_orderer_orderer_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/orderer/orderer.proto\x12\aorderer\x1a\x19proto/common/common.proto\"\xa6\x01\n" +
	"\x10BootstrapRequest\x12#\n" +
	"\rconfigtx_path\x18\x01 \x01(\tR\fconfigtxPath\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12!\n" +
	"\fgenesis_file\x18\x03 \x01(\tR\vgenesisFile\x12\x15\n" +
	"\x06msp_id\x18\x04 \x01(\tR\x05mspId\x12\x19\n" +
	"\bmsp_path\x18\x05 \x01(\tR\amspPath\"\x9b\x01\n" +
	"\x11BootstrapResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fgenesis_file\x18\x03 \x01(\tR\vgenesisFile\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\"P\n" +
	"\fBlockRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"z\n" +
	"\rBlockResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x05block\x18\x03 \x01(\v2\r.common.BlockR\x05block\"r\n" +
	"\x0eChannelRequest\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\x12#\n" +
	"\rconfigtx_path\x18\x02 \x01(\tR\fconfigtxPath\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\"v\n" +
	"\x0fChannelResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\"3\n" +
	"\x12ChannelInfoRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x85\x01\n" +
	"\x13ChannelInfoResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04info\x18\x03 \x01(\v2\x14.orderer.ChannelInfoR\x04info\"\xa2\x01\n" +
	"\vChannelInfo\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12,\n" +
	"\x12current_block_hash\x18\x03 \x01(\fR\x10currentBlockHash\x12.\n" +
	"\x13previous_block_hash\x18\x04 \x01(\fR\x11previousBlockHash\"A\n" +
	"\x14OrdererStatusRequest\x12)\n" +
	"\x10include_channels\x18\x01 \x01(\bR\x0fincludeChannels\"\x9c\x01\n" +
	"\x15OrdererStatusResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x0eorderer_status\x18\x03 \x01(\v2\x16.orderer.OrdererStatusR\rordererStatus\"\xa7\x01\n" +
	"\rOrdererStatus\x12\x1d\n" +
	"\n" +
	"orderer_id\x18\x01 \x01(\tR\tordererId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1a\n" +
	"\bchannels\x18\x03 \x03(\tR\bchannels\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion2\xb6\x03\n" +
	"\x0eOrdererService\x12K\n" +
	"\x10BootstrapNetwork\x12\x19.orderer.BootstrapRequest\x1a\x1a.orderer.BootstrapResponse\"\x00\x129\n" +
	"\vSubmitBlock\x12\x10.common.Envelope\x1a\x16.orderer.BlockResponse\"\x00\x122\n" +
	"\bGetBlock\x12\x15.orderer.BlockRequest\x1a\r.common.Block\"\x00\x12D\n" +
	"\rCreateChannel\x12\x17.orderer.ChannelRequest\x1a\x18.orderer.ChannelResponse\"\x00\x12M\n" +
	"\x0eGetChannelInfo\x12\x1b.orderer.ChannelInfoRequest\x1a\x1c.orderer.ChannelInfoResponse\"\x00\x12S\n" +
	"\x10GetOrdererStatus\x12\x1d.orderer.OrdererStatusRequest\x1a\x1e.orderer.OrdererStatusResponse\"\x00B*Z(github.com/ddr4869/minifab/proto/ordererb\x06proto3"

var (
	file_proto_orderer_orderer_proto_rawDescOnce sync.Once
	file_proto_orderer_orderer_proto_rawDescData []byte
)

func file_proto_orderer_orderer_proto_rawDescGZIP() []byte {
	file_proto_orderer_orderer_proto_rawDescOnce.Do(func() {
		file_proto_orderer_orderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderer_orderer_proto_rawDesc), len(file_proto_orderer_orderer_proto_rawDesc)))
	})
	return file_proto_orderer_orderer_proto_rawDescData
}

var file_proto_orderer_orderer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_orderer_orderer_proto_goTypes = []any{
	(*BootstrapRequest)(nil),      // 0: orderer.BootstrapRequest
	(*BootstrapResponse)(nil),     // 1: orderer.BootstrapResponse
	(*BlockRequest)(nil),          // 2: orderer.BlockRequest
	(*BlockResponse)(nil),         // 3: orderer.BlockResponse
	(*ChannelRequest)(nil),        // 4: orderer.ChannelRequest
	(*ChannelResponse)(nil),       // 5: orderer.ChannelResponse
	(*ChannelInfoRequest)(nil),    // 6: orderer.ChannelInfoRequest
	(*ChannelInfoResponse)(nil),   // 7: orderer.ChannelInfoResponse
	(*ChannelInfo)(nil),           // 8: orderer.ChannelInfo
	(*OrdererStatusRequest)(nil),  // 9: orderer.OrdererStatusRequest
	(*OrdererStatusResponse)(nil), // 10: orderer.OrdererStatusResponse
	(*OrdererStatus)(nil),         // 11: orderer.OrdererStatus
	(common.StatusCode)(0),        // 12: common.StatusCode
	(*common.Block)(nil),          // 13: common.Block
	(*common.Envelope)(nil),       // 14: common.Envelope
}
var file_proto_orderer_orderer_proto_depIdxs = []int32{
	12, // 0: orderer.BootstrapResponse.status:type_name -> common.StatusCode
	12, // 1: orderer.BlockResponse.status:type_name -> common.StatusCode
	13, // 2: orderer.BlockResponse.block:type_name -> common.Block
	12, // 3: orderer.ChannelResponse.status:type_name -> common.StatusCode
	12, // 4: orderer.ChannelInfoResponse.status:type_name -> common.StatusCode
	8,  // 5: orderer.ChannelInfoResponse.info:type_name -> orderer.ChannelInfo
	12, // 6: orderer.OrdererStatusResponse.status:type_name -> common.StatusCode
	11, // 7: orderer.OrdererStatusResponse.orderer_status:type_name -> orderer.OrdererStatus
	0,  // 8: orderer.OrdererService.BootstrapNetwork:input_type -> orderer.BootstrapRequest
	14, // 9: orderer.OrdererService.SubmitBlock:input_type -> common.Envelope
	2,  // 10: orderer.OrdererService.GetBlock:input_type -> orderer.BlockRequest
	4,  // 11: orderer.OrdererService.CreateChannel:input_type -> orderer.ChannelRequest
	6,  // 12: orderer.OrdererService.GetChannelInfo:input_type -> orderer.ChannelInfoRequest
	9,  // 13: orderer.OrdererService.GetOrdererStatus:input_type -> orderer.OrdererStatusRequest
	1,  // 14: orderer.OrdererService.BootstrapNetwork:output_type -> orderer.BootstrapResponse
	3,  // 15: orderer.OrdererService.SubmitBlock:output_type -> orderer.BlockResponse
	13, // 16: orderer.OrdererService.GetBlock:output_type -> common.Block
	5,  // 17: orderer.OrdererService.CreateChannel:output_type -> orderer.ChannelResponse
	7,  // 18: orderer.OrdererService.GetChannelInfo:output_type -> orderer.ChannelInfoResponse
	10, // 19: orderer.OrdererService.GetOrdererStatus:output_type -> orderer.OrdererStatusResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_orderer_orderer_proto_init() }
func file_proto_orderer_orderer_proto_init() {
	if File_proto_orderer_orderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderer_orderer_proto_rawDesc), len(file_proto_orderer_orderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderer_orderer_proto_goTypes,
		DependencyIndexes: file_proto_orderer_orderer_proto_depIdxs,
		MessageInfos:      file_proto_orderer_orderer_proto_msgTypes,
	}.Build()
	File_proto_orderer_orderer_proto = out.File
	file_proto_orderer_orderer_proto_goTypes = nil
	file_proto_orderer_orderer_proto_depIdxs = nil
}
