// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/orderer/orderer.proto

package orderer

import (
	common "github.com/ddr4869/minifab/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GenesisFile   string                 `protobuf:"bytes,3,opt,name=genesis_file,json=genesisFile,proto3" json:"genesis_file,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *BootstrapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BootstrapResponse) GetGenesisFile() string {
	if x != nil {
		return x.GenesisFile
	}
	return ""
}

func (x *BootstrapResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

var File_proto_orderer_orderer_proto protoreflect.FileDescriptor

const file_proto_orderer_orderer_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/orderer/orderer.proto\x12\aorderer\x1a\x19proto/common/common.proto\"\x9b\x01\n" +
	"\x11BootstrapResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fgenesis_file\x18\x03 \x01(\tR\vgenesisFile\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId2H\n" +
	"\x0eOrdererService\x126\n" +
	"\rCreateChannel\x12\x10.common.Envelope\x1a\r.common.Block\"\x00(\x010\x01B*Z(github.com/ddr4869/minifab/proto/ordererb\x06proto3"

var (
	file_proto_orderer_orderer_proto_rawDescOnce sync.Once
	file_proto_orderer_orderer_proto_rawDescData []byte
)

func file_proto_orderer_orderer_proto_rawDescGZIP() []byte {
	file_proto_orderer_orderer_proto_rawDescOnce.Do(func() {
		file_proto_orderer_orderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderer_orderer_proto_rawDesc), len(file_proto_orderer_orderer_proto_rawDesc)))
	})
	return file_proto_orderer_orderer_proto_rawDescData
}

var file_proto_orderer_orderer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_orderer_orderer_proto_goTypes = []any{
	(*BootstrapResponse)(nil), // 0: orderer.BootstrapResponse
	(common.StatusCode)(0),    // 1: common.StatusCode
	(*common.Envelope)(nil),   // 2: common.Envelope
	(*common.Block)(nil),      // 3: common.Block
}
var file_proto_orderer_orderer_proto_depIdxs = []int32{
	1, // 0: orderer.BootstrapResponse.status:type_name -> common.StatusCode
	2, // 1: orderer.OrdererService.CreateChannel:input_type -> common.Envelope
	3, // 2: orderer.OrdererService.CreateChannel:output_type -> common.Block
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_orderer_orderer_proto_init() }
func file_proto_orderer_orderer_proto_init() {
	if File_proto_orderer_orderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderer_orderer_proto_rawDesc), len(file_proto_orderer_orderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderer_orderer_proto_goTypes,
		DependencyIndexes: file_proto_orderer_orderer_proto_depIdxs,
		MessageInfos:      file_proto_orderer_orderer_proto_msgTypes,
	}.Build()
	File_proto_orderer_orderer_proto = out.File
	file_proto_orderer_orderer_proto_goTypes = nil
	file_proto_orderer_orderer_proto_depIdxs = nil
}
