// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/orderer/orderer.proto

package orderer

import (
	common "github.com/ddr4869/minifab/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.Status          `protobuf:"varint,1,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	Block         *common.Block          `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_proto_orderer_orderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_orderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_orderer_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastResponse) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *BroadcastResponse) GetBlock() *common.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_proto_orderer_orderer_proto protoreflect.FileDescriptor

const file_proto_orderer_orderer_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/orderer/orderer.proto\x12\aorderer\x1a\x19proto/common/common.proto\"`\n" +
	"\x11BroadcastResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.common.StatusR\x06status\x12#\n" +
	"\x05block\x18\x02 \x01(\v2\r.common.BlockR\x05block2U\n" +
	"\x0eOrdererService\x12C\n" +
	"\rCreateChannel\x12\x10.common.Envelope\x1a\x1a.orderer.BroadcastResponse\"\x00(\x010\x01B*Z(github.com/ddr4869/minifab/proto/ordererb\x06proto3"

var (
	file_proto_orderer_orderer_proto_rawDescOnce sync.Once
	file_proto_orderer_orderer_proto_rawDescData []byte
)

func file_proto_orderer_orderer_proto_rawDescGZIP() []byte {
	file_proto_orderer_orderer_proto_rawDescOnce.Do(func() {
		file_proto_orderer_orderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderer_orderer_proto_rawDesc), len(file_proto_orderer_orderer_proto_rawDesc)))
	})
	return file_proto_orderer_orderer_proto_rawDescData
}

var file_proto_orderer_orderer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_orderer_orderer_proto_goTypes = []any{
	(*BroadcastResponse)(nil), // 0: orderer.BroadcastResponse
	(common.Status)(0),        // 1: common.Status
	(*common.Block)(nil),      // 2: common.Block
	(*common.Envelope)(nil),   // 3: common.Envelope
}
var file_proto_orderer_orderer_proto_depIdxs = []int32{
	1, // 0: orderer.BroadcastResponse.status:type_name -> common.Status
	2, // 1: orderer.BroadcastResponse.block:type_name -> common.Block
	3, // 2: orderer.OrdererService.CreateChannel:input_type -> common.Envelope
	0, // 3: orderer.OrdererService.CreateChannel:output_type -> orderer.BroadcastResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_orderer_orderer_proto_init() }
func file_proto_orderer_orderer_proto_init() {
	if File_proto_orderer_orderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderer_orderer_proto_rawDesc), len(file_proto_orderer_orderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderer_orderer_proto_goTypes,
		DependencyIndexes: file_proto_orderer_orderer_proto_depIdxs,
		MessageInfos:      file_proto_orderer_orderer_proto_msgTypes,
	}.Build()
	File_proto_orderer_orderer_proto = out.File
	file_proto_orderer_orderer_proto_goTypes = nil
	file_proto_orderer_orderer_proto_depIdxs = nil
}
