// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 상태 코드
type StatusCode int32

const (
	StatusCode_OK                            StatusCode = 0
	StatusCode_INVALID_ARGUMENT              StatusCode = 1
	StatusCode_NOT_FOUND                     StatusCode = 2
	StatusCode_ALREADY_EXISTS                StatusCode = 3
	StatusCode_PERMISSION_DENIED             StatusCode = 4
	StatusCode_INTERNAL_ERROR                StatusCode = 5
	StatusCode_UNAVAILABLE                   StatusCode = 6
	StatusCode_TIMEOUT                       StatusCode = 7
	StatusCode_INVALID_SIGNATURE             StatusCode = 8
	StatusCode_INVALID_CERTIFICATE           StatusCode = 9
	StatusCode_CHANNEL_NOT_FOUND             StatusCode = 10
	StatusCode_TRANSACTION_VALIDATION_FAILED StatusCode = 11
	StatusCode_ENDORSEMENT_POLICY_FAILURE    StatusCode = 12
	StatusCode_NETWORK_ERROR                 StatusCode = 13
	StatusCode_CONSENSUS_ERROR               StatusCode = 14
	StatusCode_LEDGER_ERROR                  StatusCode = 15
	StatusCode_MSP_ERROR                     StatusCode = 16
	StatusCode_BLOCK_VALIDATION_FAILED       StatusCode = 17
	StatusCode_INVALID_BLOCK                 StatusCode = 18
	StatusCode_INVALID_TRANSACTION_FORMAT    StatusCode = 19
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "OK",
		1:  "INVALID_ARGUMENT",
		2:  "NOT_FOUND",
		3:  "ALREADY_EXISTS",
		4:  "PERMISSION_DENIED",
		5:  "INTERNAL_ERROR",
		6:  "UNAVAILABLE",
		7:  "TIMEOUT",
		8:  "INVALID_SIGNATURE",
		9:  "INVALID_CERTIFICATE",
		10: "CHANNEL_NOT_FOUND",
		11: "TRANSACTION_VALIDATION_FAILED",
		12: "ENDORSEMENT_POLICY_FAILURE",
		13: "NETWORK_ERROR",
		14: "CONSENSUS_ERROR",
		15: "LEDGER_ERROR",
		16: "MSP_ERROR",
		17: "BLOCK_VALIDATION_FAILED",
		18: "INVALID_BLOCK",
		19: "INVALID_TRANSACTION_FORMAT",
	}
	StatusCode_value = map[string]int32{
		"OK":                            0,
		"INVALID_ARGUMENT":              1,
		"NOT_FOUND":                     2,
		"ALREADY_EXISTS":                3,
		"PERMISSION_DENIED":             4,
		"INTERNAL_ERROR":                5,
		"UNAVAILABLE":                   6,
		"TIMEOUT":                       7,
		"INVALID_SIGNATURE":             8,
		"INVALID_CERTIFICATE":           9,
		"CHANNEL_NOT_FOUND":             10,
		"TRANSACTION_VALIDATION_FAILED": 11,
		"ENDORSEMENT_POLICY_FAILURE":    12,
		"NETWORK_ERROR":                 13,
		"CONSENSUS_ERROR":               14,
		"LEDGER_ERROR":                  15,
		"MSP_ERROR":                     16,
		"BLOCK_VALIDATION_FAILED":       17,
		"INVALID_BLOCK":                 18,
		"INVALID_TRANSACTION_FORMAT":    19,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_common_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_common_common_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{0}
}

// 메시지 타입
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_BLOCK       MessageType = 1 // 블록 전송
	MessageType_MESSAGE_TYPE_TRANSACTION MessageType = 2 // 트랜잭션 전송
	MessageType_MESSAGE_TYPE_CONFIG      MessageType = 3 // 설정 전송
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_BLOCK",
		2: "MESSAGE_TYPE_TRANSACTION",
		3: "MESSAGE_TYPE_CONFIG",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_BLOCK":       1,
		"MESSAGE_TYPE_TRANSACTION": 2,
		"MESSAGE_TYPE_CONFIG":      3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_common_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_common_common_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{1}
}

// 블록 타입 구분
type BlockType int32

const (
	BlockType_BLOCK_TYPE_UNSPECIFIED BlockType = 0
	BlockType_BLOCK_TYPE_CONFIG      BlockType = 1 // 설정 블록
	BlockType_BLOCK_TYPE_DATA        BlockType = 2 // 일반 트랜잭션 블록
)

// Enum value maps for BlockType.
var (
	BlockType_name = map[int32]string{
		0: "BLOCK_TYPE_UNSPECIFIED",
		1: "BLOCK_TYPE_CONFIG",
		2: "BLOCK_TYPE_DATA",
	}
	BlockType_value = map[string]int32{
		"BLOCK_TYPE_UNSPECIFIED": 0,
		"BLOCK_TYPE_CONFIG":      1,
		"BLOCK_TYPE_DATA":        2,
	}
)

func (x BlockType) Enum() *BlockType {
	p := new(BlockType)
	*p = x
	return p
}

func (x BlockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_common_proto_enumTypes[2].Descriptor()
}

func (BlockType) Type() protoreflect.EnumType {
	return &file_proto_common_common_proto_enumTypes[2]
}

func (x BlockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockType.Descriptor instead.
func (BlockType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{2}
}

// Envelope - 노드 간 통신용 봉투
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`     // 직렬화된 Payload
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // payload 서명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Payload - 실제 데이터를 담는 구조
type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 메시지 헤더
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     // 직렬화된 데이터 (Block, Transaction 등)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Header - 메시지 헤더
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // 중복 방지용 nonce
	Identity      *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=common.MessageType" json:"type,omitempty"`   // 메시지 타입
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // 채널 ID
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 타임스탬프
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Header) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Header) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Header) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Header) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Block - 완전한 블록 구조
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`     // Block Header
	Data          *BlockData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // Block Data
	Metadata      *BlockMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // Block Metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetData() *BlockData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetMetadata() *BlockMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Block Header - 블록 헤더
type BlockHeader struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Number           uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`                                                 // Block Number (0부터 시작)
	CurrentBlockHash []byte                 `protobuf:"bytes,2,opt,name=current_block_hash,json=currentBlockHash,proto3" json:"current_block_hash,omitempty"`    // 현재 Block Hash
	PreviousHash     []byte                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`                  // 이전 Block Header Hash
	HeaderType       BlockType              `protobuf:"varint,4,opt,name=header_type,json=headerType,proto3,enum=common.BlockType" json:"header_type,omitempty"` // 블록 타입 구분
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_proto_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *BlockHeader) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockHeader) GetCurrentBlockHash() []byte {
	if x != nil {
		return x.CurrentBlockHash
	}
	return nil
}

func (x *BlockHeader) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *BlockHeader) GetHeaderType() BlockType {
	if x != nil {
		return x.HeaderType
	}
	return BlockType_BLOCK_TYPE_UNSPECIFIED
}

// Block Data - Ordering service에 의해 정렬된 트랜잭션들
type BlockData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"` // 트랜잭션 데이터 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_proto_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *BlockData) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Block Metadata - 블록 검증을 위한 메타데이터
type BlockMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Signature        []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`                                       // 서명 - orderer
	ValidationBitmap []byte                 `protobuf:"bytes,2,opt,name=validation_bitmap,json=validationBitmap,proto3" json:"validation_bitmap,omitempty"` // 트랜잭션 Valid/Invalid 비트맵
	AccumulatedHash  []byte                 `protobuf:"bytes,3,opt,name=accumulated_hash,json=accumulatedHash,proto3" json:"accumulated_hash,omitempty"`    // fork 확인을 위한 축적된 해시값
	Identity         *Identity              `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockMetadata) Reset() {
	*x = BlockMetadata{}
	mi := &file_proto_common_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMetadata) ProtoMessage() {}

func (x *BlockMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMetadata.ProtoReflect.Descriptor instead.
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *BlockMetadata) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockMetadata) GetValidationBitmap() []byte {
	if x != nil {
		return x.ValidationBitmap
	}
	return nil
}

func (x *BlockMetadata) GetAccumulatedHash() []byte {
	if x != nil {
		return x.AccumulatedHash
	}
	return nil
}

func (x *BlockMetadata) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

// Transaction - 트랜잭션 구조
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // 트랜잭션 ID
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`       // 트랜잭션 데이터
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`   // 서명 - endorser
	Identity      *Identity              `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 트랜잭션 생성 시간
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_common_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Transaction) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Transaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       []byte                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	MspId         string                 `protobuf:"bytes,2,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_proto_common_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *Identity) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *Identity) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

var File_proto_common_common_proto protoreflect.FileDescriptor

const file_proto_common_common_proto_rawDesc = "" +
	"\n" +
	"\x19proto/common/common.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\bEnvelope\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"E\n" +
	"\aPayload\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.common.HeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xce\x01\n" +
	"\x06Header\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12,\n" +
	"\bidentity\x18\x02 \x01(\v2\x10.common.IdentityR\bidentity\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.common.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8e\x01\n" +
	"\x05Block\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.common.BlockHeaderR\x06header\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.common.BlockDataR\x04data\x121\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.common.BlockMetadataR\bmetadata\"\xac\x01\n" +
	"\vBlockHeader\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12,\n" +
	"\x12current_block_hash\x18\x02 \x01(\fR\x10currentBlockHash\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\fR\fpreviousHash\x122\n" +
	"\vheader_type\x18\x04 \x01(\x0e2\x11.common.BlockTypeR\n" +
	"headerType\"/\n" +
	"\tBlockData\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\"\xb3\x01\n" +
	"\rBlockMetadata\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12+\n" +
	"\x11validation_bitmap\x18\x02 \x01(\fR\x10validationBitmap\x12)\n" +
	"\x10accumulated_hash\x18\x03 \x01(\fR\x0faccumulatedHash\x12,\n" +
	"\bidentity\x18\x04 \x01(\v2\x10.common.IdentityR\bidentity\"\xa6\x01\n" +
	"\vTransaction\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12,\n" +
	"\bidentity\x18\x04 \x01(\v2\x10.common.IdentityR\bidentity\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\";\n" +
	"\bIdentity\x12\x18\n" +
	"\acreator\x18\x01 \x01(\fR\acreator\x12\x15\n" +
	"\x06msp_id\x18\x02 \x01(\tR\x05mspId*\xb9\x03\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x03\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x04\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x05\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x06\x12\v\n" +
	"\aTIMEOUT\x10\a\x12\x15\n" +
	"\x11INVALID_SIGNATURE\x10\b\x12\x17\n" +
	"\x13INVALID_CERTIFICATE\x10\t\x12\x15\n" +
	"\x11CHANNEL_NOT_FOUND\x10\n" +
	"\x12!\n" +
	"\x1dTRANSACTION_VALIDATION_FAILED\x10\v\x12\x1e\n" +
	"\x1aENDORSEMENT_POLICY_FAILURE\x10\f\x12\x11\n" +
	"\rNETWORK_ERROR\x10\r\x12\x13\n" +
	"\x0fCONSENSUS_ERROR\x10\x0e\x12\x10\n" +
	"\fLEDGER_ERROR\x10\x0f\x12\r\n" +
	"\tMSP_ERROR\x10\x10\x12\x1b\n" +
	"\x17BLOCK_VALIDATION_FAILED\x10\x11\x12\x11\n" +
	"\rINVALID_BLOCK\x10\x12\x12\x1e\n" +
	"\x1aINVALID_TRANSACTION_FORMAT\x10\x13*z\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_BLOCK\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_TYPE_TRANSACTION\x10\x02\x12\x17\n" +
	"\x13MESSAGE_TYPE_CONFIG\x10\x03*S\n" +
	"\tBlockType\x12\x1a\n" +
	"\x16BLOCK_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BLOCK_TYPE_CONFIG\x10\x01\x12\x13\n" +
	"\x0fBLOCK_TYPE_DATA\x10\x02B)Z'github.com/ddr4869/minifab/proto/commonb\x06proto3"

var (
	file_proto_common_common_proto_rawDescOnce sync.Once
	file_proto_common_common_proto_rawDescData []byte
)

func file_proto_common_common_proto_rawDescGZIP() []byte {
	file_proto_common_common_proto_rawDescOnce.Do(func() {
		file_proto_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_common_proto_rawDesc), len(file_proto_common_common_proto_rawDesc)))
	})
	return file_proto_common_common_proto_rawDescData
}

var file_proto_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_common_common_proto_goTypes = []any{
	(StatusCode)(0),               // 0: common.StatusCode
	(MessageType)(0),              // 1: common.MessageType
	(BlockType)(0),                // 2: common.BlockType
	(*Envelope)(nil),              // 3: common.Envelope
	(*Payload)(nil),               // 4: common.Payload
	(*Header)(nil),                // 5: common.Header
	(*Block)(nil),                 // 6: common.Block
	(*BlockHeader)(nil),           // 7: common.BlockHeader
	(*BlockData)(nil),             // 8: common.BlockData
	(*BlockMetadata)(nil),         // 9: common.BlockMetadata
	(*Transaction)(nil),           // 10: common.Transaction
	(*Identity)(nil),              // 11: common.Identity
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_common_common_proto_depIdxs = []int32{
	5,  // 0: common.Payload.header:type_name -> common.Header
	11, // 1: common.Header.identity:type_name -> common.Identity
	1,  // 2: common.Header.type:type_name -> common.MessageType
	12, // 3: common.Header.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 4: common.Block.header:type_name -> common.BlockHeader
	8,  // 5: common.Block.data:type_name -> common.BlockData
	9,  // 6: common.Block.metadata:type_name -> common.BlockMetadata
	2,  // 7: common.BlockHeader.header_type:type_name -> common.BlockType
	11, // 8: common.BlockMetadata.identity:type_name -> common.Identity
	11, // 9: common.Transaction.identity:type_name -> common.Identity
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_common_common_proto_init() }
func file_proto_common_common_proto_init() {
	if File_proto_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_common_proto_rawDesc), len(file_proto_common_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_common_proto_goTypes,
		DependencyIndexes: file_proto_common_common_proto_depIdxs,
		EnumInfos:         file_proto_common_common_proto_enumTypes,
		MessageInfos:      file_proto_common_common_proto_msgTypes,
	}.Build()
	File_proto_common_common_proto = out.File
	file_proto_common_common_proto_goTypes = nil
	file_proto_common_common_proto_depIdxs = nil
}
