Organizations:
  - Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ca/ca-client/orderer0/msp
    OrdererEndpoints: [127.0.0.1:7050]
  - Name: Org1MSP
    ID: Org1MSP
    MSPDir: ca/ca-client/peer0/msp
    AnchorPeers:
      - Host: 127.0.0.1
        Port: 7051

Orderer:
  Type: solo
  BatchTimeout: 200ms
  BatchSize:
    MaxMessageCount: 300
    AbsoluteMaxBytes: 128MB
    PreferredMaxBytes: 128MB
  Organizations: [OrdererOrg]

Channel:
  Policies: all
  
Profiles:
  SystemChannel:
    Orderer:
      Type: solo
      BatchTimeout: 200ms
      BatchSize:
        MaxMessageCount: 300
        AbsoluteMaxBytes: 128MB
        PreferredMaxBytes: 128MB
      Organizations: [OrdererOrg]
    Organizations: [OrdererOrg]
  AppChannel:
    Application:
      Organizations: [Org1MSP]

