// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/peer/peer.proto

package peer

import (
	common "github.com/ddr4869/minifab/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessBlockResponse - 블록 처리 응답
type ProcessBlockResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BlockNumber         uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ValidTransactions   int32                  `protobuf:"varint,4,opt,name=valid_transactions,json=validTransactions,proto3" json:"valid_transactions,omitempty"`
	InvalidTransactions int32                  `protobuf:"varint,5,opt,name=invalid_transactions,json=invalidTransactions,proto3" json:"invalid_transactions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessBlockResponse) Reset() {
	*x = ProcessBlockResponse{}
	mi := &file_proto_peer_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBlockResponse) ProtoMessage() {}

func (x *ProcessBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBlockResponse.ProtoReflect.Descriptor instead.
func (*ProcessBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_peer_peer_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessBlockResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *ProcessBlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessBlockResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ProcessBlockResponse) GetValidTransactions() int32 {
	if x != nil {
		return x.ValidTransactions
	}
	return 0
}

func (x *ProcessBlockResponse) GetInvalidTransactions() int32 {
	if x != nil {
		return x.InvalidTransactions
	}
	return 0
}

// JoinChannelRequest - 채널 참여 요청
type JoinChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	GenesisBlock  *common.Block          `protobuf:"bytes,2,opt,name=genesis_block,json=genesisBlock,proto3" json:"genesis_block,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerIdentity  []byte                 `protobuf:"bytes,4,opt,name=peer_identity,json=peerIdentity,proto3" json:"peer_identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannelRequest) Reset() {
	*x = JoinChannelRequest{}
	mi := &file_proto_peer_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannelRequest) ProtoMessage() {}

func (x *JoinChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannelRequest.ProtoReflect.Descriptor instead.
func (*JoinChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_peer_peer_proto_rawDescGZIP(), []int{1}
}

func (x *JoinChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *JoinChannelRequest) GetGenesisBlock() *common.Block {
	if x != nil {
		return x.GenesisBlock
	}
	return nil
}

func (x *JoinChannelRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *JoinChannelRequest) GetPeerIdentity() []byte {
	if x != nil {
		return x.PeerIdentity
	}
	return nil
}

// JoinChannelResponse - 채널 참여 응답
type JoinChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.StatusCode      `protobuf:"varint,1,opt,name=status,proto3,enum=common.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CurrentHeight uint64                 `protobuf:"varint,4,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannelResponse) Reset() {
	*x = JoinChannelResponse{}
	mi := &file_proto_peer_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannelResponse) ProtoMessage() {}

func (x *JoinChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_peer_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannelResponse.ProtoReflect.Descriptor instead.
func (*JoinChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_peer_peer_proto_rawDescGZIP(), []int{2}
}

func (x *JoinChannelResponse) GetStatus() common.StatusCode {
	if x != nil {
		return x.Status
	}
	return common.StatusCode(0)
}

func (x *JoinChannelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *JoinChannelResponse) GetCurrentHeight() uint64 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

var File_proto_peer_peer_proto protoreflect.FileDescriptor

const file_proto_peer_peer_proto_rawDesc = "" +
	"\n" +
	"\x15proto/peer/peer.proto\x12\x04peer\x1a\x19proto/common/common.proto\"\xe1\x01\n" +
	"\x14ProcessBlockResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12-\n" +
	"\x12valid_transactions\x18\x04 \x01(\x05R\x11validTransactions\x121\n" +
	"\x14invalid_transactions\x18\x05 \x01(\x05R\x13invalidTransactions\"\xa5\x01\n" +
	"\x12JoinChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x122\n" +
	"\rgenesis_block\x18\x02 \x01(\v2\r.common.BlockR\fgenesisBlock\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\x12#\n" +
	"\rpeer_identity\x18\x04 \x01(\fR\fpeerIdentity\"\xa1\x01\n" +
	"\x13JoinChannelResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.common.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12%\n" +
	"\x0ecurrent_height\x18\x04 \x01(\x04R\rcurrentHeight2\x93\x01\n" +
	"\vPeerService\x12>\n" +
	"\fProcessBlock\x12\x10.common.Envelope\x1a\x1a.peer.ProcessBlockResponse\"\x00\x12D\n" +
	"\vJoinChannel\x12\x18.peer.JoinChannelRequest\x1a\x19.peer.JoinChannelResponse\"\x00B'Z%github.com/ddr4869/minifab/proto/peerb\x06proto3"

var (
	file_proto_peer_peer_proto_rawDescOnce sync.Once
	file_proto_peer_peer_proto_rawDescData []byte
)

func file_proto_peer_peer_proto_rawDescGZIP() []byte {
	file_proto_peer_peer_proto_rawDescOnce.Do(func() {
		file_proto_peer_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_peer_peer_proto_rawDesc), len(file_proto_peer_peer_proto_rawDesc)))
	})
	return file_proto_peer_peer_proto_rawDescData
}

var file_proto_peer_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_peer_peer_proto_goTypes = []any{
	(*ProcessBlockResponse)(nil), // 0: peer.ProcessBlockResponse
	(*JoinChannelRequest)(nil),   // 1: peer.JoinChannelRequest
	(*JoinChannelResponse)(nil),  // 2: peer.JoinChannelResponse
	(common.StatusCode)(0),       // 3: common.StatusCode
	(*common.Block)(nil),         // 4: common.Block
	(*common.Envelope)(nil),      // 5: common.Envelope
}
var file_proto_peer_peer_proto_depIdxs = []int32{
	3, // 0: peer.ProcessBlockResponse.status:type_name -> common.StatusCode
	4, // 1: peer.JoinChannelRequest.genesis_block:type_name -> common.Block
	3, // 2: peer.JoinChannelResponse.status:type_name -> common.StatusCode
	5, // 3: peer.PeerService.ProcessBlock:input_type -> common.Envelope
	1, // 4: peer.PeerService.JoinChannel:input_type -> peer.JoinChannelRequest
	0, // 5: peer.PeerService.ProcessBlock:output_type -> peer.ProcessBlockResponse
	2, // 6: peer.PeerService.JoinChannel:output_type -> peer.JoinChannelResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_peer_peer_proto_init() }
func file_proto_peer_peer_proto_init() {
	if File_proto_peer_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_peer_peer_proto_rawDesc), len(file_proto_peer_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_peer_peer_proto_goTypes,
		DependencyIndexes: file_proto_peer_peer_proto_depIdxs,
		MessageInfos:      file_proto_peer_peer_proto_msgTypes,
	}.Build()
	File_proto_peer_peer_proto = out.File
	file_proto_peer_peer_proto_goTypes = nil
	file_proto_peer_peer_proto_depIdxs = nil
}
